services:
  backend:
    build:
      context: backend
      target: builder
    restart: always
    command: ["flask", "run"]
    ports:
      - 8000:8000
    networks:
      - backnet


networks:
  backnet:
